// AUTO-GENERATED by scripts/set-env.js — do not edit manually
export const environment = {
  production: true,
  weatherApiBase: 'https://api.open-meteo.com/v1',
  geocodingApiBase: 'https://geocoding-api.open-meteo.com/v1',
  airQualityApiBase: 'https://air-quality-api.open-meteo.com/v1',
  openWeatherMapKey: '',
  openWeatherMapBase: 'https://api.openweathermap.org/data/2.5',
  mapTileUrl: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
  mapAttribution: '&copy; OpenStreetMap contributors',
};
