// Runs before `ng build` to inject environment variables into Angular environment files.
// On Vercel, env vars come from the dashboard. Locally, use .env.development or .env.production.

const { writeFileSync } = require('fs');
const { resolve } = require('path');

const isProduction = process.env['NODE_ENV'] === 'production';

const env = {
  production: isProduction,
  weatherApiBase: process.env['WEATHER_API_BASE'] || 'https://api.open-meteo.com/v1',
  geocodingApiBase: process.env['GEOCODING_API_BASE'] || 'https://geocoding-api.open-meteo.com/v1',
  airQualityApiBase: process.env['AIR_QUALITY_API_BASE'] || 'https://air-quality-api.open-meteo.com/v1',
  openWeatherMapKey: process.env['OPENWEATHERMAP_API_KEY'] || '',
  openWeatherMapBase: process.env['OPENWEATHERMAP_BASE'] || 'https://api.openweathermap.org/data/2.5',
  mapTileUrl: process.env['MAP_TILE_URL'] || 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
  mapAttribution: process.env['MAP_ATTRIBUTION'] || '&copy; OpenStreetMap contributors',
};

const content = `// AUTO-GENERATED by scripts/set-env.js — do not edit manually
export const environment = ${JSON.stringify(env, null, 2)};
`;

const targetFile = isProduction
  ? resolve(__dirname, '../src/environments/environment.prod.ts')
  : resolve(__dirname, '../src/environments/environment.ts');

writeFileSync(targetFile, content);
console.log(`Environment written to ${targetFile} (production=${isProduction})`);
